export const officesIds = {
'ADMINIST. GRAL':{id:'107',icon:'ClipboardSignature'},
'ADMINISTRACION GENERAL':{id:'104',icon:'Bell'},
'ADMINISTRACION Y FINANZAS':{id:'110',icon:'Bell'},
'ADULTOS MAYORES/DISCAPACIDAD':{id:'77',icon:'Accessibility'},
'ALUMBRADO':{id:'69',icon:'Lightbulb'},
'AMBIENTE':{id:'37',icon:'Bell'},
'ASESORIA LETRADA':{id:'8',icon:'Bell'},
'ASISTENCIA_SOCIAL':{id:'13',icon:'Bell'},
'ATENCION AL CIUDADANO':{id:'128',icon:'Bell'},
'AUD. CONCESION SERV.PUBLICOS':{id:'79',icon:'Bell'},
'BARRIDO':{id:'68',icon:'Bell'},
'BIBLIOTECA':{id:'80',icon:'Bell'},
'C.O.M':{id:'55',icon:'Bell'},
'CADINA':{id:'86',icon:'Bell'},
'CAJA':{id:'18',icon:'Bell'},
'CAPACITACION Y DOCENCIA':{id:'105',icon:'Bell'},
'CAPRIM':{id:'87',icon:'Bell'},
'CATASTRO':{id:'3',icon:'Newspaper'},
'CEMENTERIOS':{id:'50',icon:'Bell'},
'CEREMONIAL Y PROTOCOLO':{id:'119',icon:'Bell'},
'CIAC':{id:'83',icon:'Bell'},
'COMERCIO E INDUSTRIA':{id:'7',icon:'Factory'},
'COMPRAS':{id:'24',icon:'Banknote'},
'COMUNICACION Y PRENSA':{id:'63',icon:'MessageSquare'},
'CONCEJO DELIBERANTE':{id:'52',icon:'MessagesSquare'},
'CONTADURIA':{id:'12',icon:'Calculator'},
'CONTROL DE GESTION':{id:'48',icon:'Bell'},
'CUERPOS ARTISTICOS':{id:'81',icon:'Bell'},
'CULTURA':{id:'43',icon:'Bell'},
'CULTURA_Y_DEPORTES':{id:'11',icon:'Bell'},
'DEFENSA CIVIL':{id:'120',icon:'Bell'},
'DEMVA':{id:'91',icon:'Bell'},
'DEPORTES':{id:'44',icon:'Bell'},
'DEPOSITO':{id:'78',icon:'Bell'},
'DESARROLLO ECONOMICO':{id:'109',icon:'Bell'},
'DESARROLLO HUMANO':{id:'101',icon:'Bell'},
'DESARROLLO SOCIAL':{id:'39',icon:'Bell'},
'DESMALEZADO/PODA':{id:'70',icon:'Bell'},
'DESMALEZAMIENTO':{id:'115',icon:'Bell'},
'DESPACHO':{id:'28',icon:'Bell'},
'DIAGNOSTICO POR IMAGENES':{id:'92',icon:'Bell'},
'DIR. INSPEC. GRALES.':{id:'108',icon:'Bell'},
'DIRECCION DE HABILITACION DE NEGOCIOS':{id:'124',icon:'Bell'},
'DIRECCIÓN DE PARTICIPACIÓN CIUDADANA':{id:'35',icon:'Bell'},
'EDIFICIOS PUBLICOS':{id:'65',icon:'Bell'},
'EDUCACION':{id:'103',icon:'Bell'},
'EMPRENDEDORES':{id:'58',icon:'Bell'},
'ENFERMERIA':{id:'95',icon:'HeartPulse'},
'ESPACIOS VERDES':{id:'71',icon:'Leaf'},
'ESPECIALIDADES MEDICAS':{id:'88',icon:'Stethoscope'},
'ESPECTACULOS PUBLICOS':{id:'33',icon:'Shrub'},
'EXTRACCION  Y PODA DE ARBOLES':{id:'116',icon:'Trees'},
'FARMACIA':{id:'90',icon:'Pill'},
'GENERAL':{id:'17',icon:'Bell'},
'GESTION AMBIENTAL':{id:'127',icon:'Trees'},
'GOBIERNO':{id:'99',icon:'Bell'},
'GOBIERNO ABIERTO':{id:'61',icon:'Bell'},
'GUARDIA':{id:'93',icon:'Bell'},
'HABILITACION DE NEGOCIOS Y CTROL. DE ALI':{id:'25',icon:'Bell'},
'HABITAT SOCIAL':{id:'75',icon:'Bell'},
'HACIENDA':{id:'100',icon:'Receipt'},
'HOGAR DE DIA':{id:'73',icon:'Bell'},
'HOSPITAL':{id:'41',icon:'Bell'},
'INFRACCIONES TRANSITO':{id:'26',icon:'Bell'},
'INMUEBLES':{id:'23',icon:'Bell'},
'INSPECCIONES GENERALES':{id:'10',icon:'Bell'},
'INTENDENCIA':{id:'16',icon:'Bell'},
'JUZGADO DE FALTAS':{id:'122',icon:'Scale'},
'JUZGADO DE PAZ':{id:'98',icon:'Bell'},
'LABORATORIO':{id:'94',icon:'Bell'},
'LEGAL Y TECNICA-DESPACHO Y ARCHIVO':{id:'62',icon:'Bell'},
'LICENCIA DE CONDUCIR':{id:'30',icon:'Contact'},
'MANTENIMIENTO DE CALLES':{id:'64',icon:'Milestone'},
'MANTENIMIENTO GENERAL':{id:'38',icon:'Bell'},
'MEDICA':{id:'111',icon:'Bell'},
'MESA ENTRADA WEB':{id:'125',icon:'Bell'},
'MESA_ENTRADAS':{id:'2',icon:'Bell'},
'NIÑEZ, ADOLESCENCIA Y FLIA.':{id:'72',icon:'Bell'},
'OBRAS Y SERVICIOS PUBLICOS':{id:'112',icon:'Bell'},
'OBRAS_PRIVADAS':{id:'4',icon:'Bell'},
'OBRAS_PUBLICAS':{id:'9',icon:'Bell'},
'OFICINA AUTOMOTOR':{id:'6',icon:'Car'},
'OFICINA DE EMPLEO':{id:'54',icon:'Bell'},
'OFICINA DE EMPLEONOUSAR':{id:'59',icon:'Bell'},
'PERSONAL':{id:'14',icon:'PersonStanding'},
'PLANEAMIENTO Y URBANISMO':{id:'66',icon:'Bell'},
'PLANIF. Y CONTROL DE GESTION':{id:'123',icon:'Bell'},
'PLANIFICACION ESTRATEGICA':{id:'47',icon:'Bell'},
'PLANIFICACION Y CONTROL DE GESTION':{id:'46',icon:'Bell'},
'POLIDEPORTIVO ':{id:'57',icon:'Bell'},
'PROCURACION':{id:'20',icon:'Bell'},
'PROCURACION ADMINISTRATIVA':{id:'126',icon:'Bell'},
'PRODUCCION':{id:'60',icon:'Bell'},
'PROMOCION SOCIAL':{id:'76',icon:'Bell'},
'PROYECTOS Y PROGRAMAS DE SALUD':{id:'89',icon:'Bell'},
'R.S.U. / RECICLADO':{id:'67',icon:'Bell'},
'RECOLEC., TRATAM.Y DISPOS.PODA':{id:'118',icon:'Bell'},
'RECOLECCION R.S.U.':{id:'114',icon:'Bell'},
'RECURSOS HUMANOS':{id:'49',icon:'PersonStanding'},
'RECURSOS TRIBUTARIOS':{id:'5',icon:'Bell'},
'RED DE INSTITUCIONES EDUCATIVAS':{id:'85',icon:'Bell'},
'REFUGIO CANINO':{id:'113',icon:'Dog'},
'REGISTRO CIVIL':{id:'34',icon:'Bell'},
'SALUD':{id:'102',icon:'Bell'},
'SEC. DE DESARROLLO HUMANO':{id:'42',icon:'Bell'},
'SEC. DE DESARROLLO URBANO':{id:'36',icon:'Bell'},
'SEC. DE GOBIERNO':{id:'27',icon:'Bell'},
'SEC. DE HACIENDA':{id:'32',icon:'Landmark'},
'SEC. DE SALUD':{id:'40',icon:'Bell'},
'SECRETARIA PRIVADA':{id:'106',icon:'Bell'},
'SEGURIDAD CIUDADANA ':{id:'15',icon:'Bell'},
'SERVICIOS DE SEPELIOS':{id:'74',icon:'Bell'},
'SERVICIOS_PUBLICOS':{id:'21',icon:'Bell'},
'SIN DESTINO':{id:'1',icon:'CircleOff'},
'SIN USO':{id:'22',icon:'Bell'},
'SISTEMAS':{id:'19',icon:'Code'},
'SUMARIOS':{id:'121',icon:'Layers'},
'TALLER':{id:'53',icon:'Wrench'},
'TALLERES':{id:'82',icon:'Wrench'},
'TESORERIA':{id:'31',icon:'PiggyBank'},
'TRANSPORTE':{id:'29',icon:'Bus'},
'TRANSPORTE Y DISP.FINAL R.S.U. Y PELIGRO':{id:'117',icon:'Bus'},
'TRIBUNAL DE CUENTAS':{id:'51',icon:'Layers'},
'TURISMO':{id:'45',icon:'Compass'},
}

export const procuracionIds = {
  'AUTOMOTOR':{id:'107',icon:'Car'},
  'ADMINISTRACION GENERAL':{id:'104',icon:'Bell'},
  'ADMINISTRACION Y FINANZAS':{id:'110',icon:'Bell'},
  }
